version: '3'
services:
  mongodb:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
  node:
    image: node:20.15.1
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    command: npm start