version: '3'
services:
  mongodb:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
  node:
    image: node:20.15.1
    working_dir: /pandavideo-backend
    volumes:
      - ./pandavideo-backend:/pandavideo-backend
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    command: bash -c "npm install && npm start"
  vue:
    image: node:20.15.1 
    working_dir: /pandavideo-frontend
    volumes:
      - ./pandavideo-frontend:/pandavideo-frontend
    ports:
      - '8080:8080' 
    command: bash -c "npm install && npm run serve" 
    environment:
      CHOKIDAR_USEPOLLING: true
  